<?php
/*
Copyright (C) 2007 Stephane Graber <stgraber@ubuntu.com>

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
*/

require_once "ideatorrent.function.php"; 
require_once "ideatorrent.display.php"; 
require_once "controller.php";

function ideatorrent_access($op, $node) {
	return TRUE;
}


function ideatorrent_perm()
{
	//Get the controller instance
	$controller = QAPollController::getInstance();

	//Get and return the permissions
	return $controller->get_permissions();
}

function ideatorrent_menu() {
	$items = array();
	$items['ideatorrent'] = array(
		'title' => 'IdeaTorrent',
		'page callback' => 'ideatorrent_main',
		'access arguments' => array('access content'), 
		'type' => MENU_NORMAL_ITEM, 
		'weight' => -9
		);
	return $items;
}
?>
